### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by mikejpeters** [philmerrell/capacitor-firebase-analytics#13]
I see you're looking for someone to take over this project. I'm interested - I've recently written another capacitor plugin (https://github.com/boundstate/capacitor-branch-deep-links) so I think I have enough experience to handle this.

**Comment by mckelveygreg** [comment]
Just checked out your fork, thanks for taking up the torch!
I'm just looking in to using the project, is this going to switch over to your new branch soon?

**Comment by ravenberg** [comment]
Hi, I am looking forward to use this project as well.

**Comment by mikejpeters** [comment]
@philmerrell any thoughts?

**Comment by Boosten** [comment]
Perhaps the owner of this repo is willing to contribute https://github.com/stewwan/capacitor-analytics. Or maybe we can combine these two repos to one solid one?

**Comment by mckelveygreg** [comment]
So.... I'm looking at using this again for another project, did the repo ever get moved over officially?
