### ISSUE TITLE
Statement in readme

### ISSUE THREAD

**Issue by vitorplopes** [philmerrell/capacitor-firebase-analytics#2]
Does the statement 

> don't use this yet.

is still valid at 0.3.2 version?

If so, which are the missing features?

Regards.

**Comment by achhaiba** [comment]
This plugin seems to expose all the necessary features for Firebase Analytics tracking.
As @vitorplopes says, Why it's not ready to use?
I'm an iOS developer, we can collaborate together to improve it.
Best regards.

**Comment by oori** [comment]
@philmerrell could you comment on this?  thanks.

**Comment by philmerrell** [comment]
Hey all...

The statement "don't use this yet" can probably be removed. I have been trying to be cautious, but I was able to successfully install and use the plugin. If someone could verify that outside of my machine I would feel more comfortable. I can verify the methods on both iOS and Android work, it's the refactoring into a Capacitor plugin that I'm being cautious with.

If someone can verify the install process is smooth, I will remove the comment. When I have a moment to spare I can also verify this on multiple projects.

Thanks for caring! If you have any feedback please let me know.
